config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # g scaffold criou esses recursos (CRUD) abaixo:
  resources :blog_posts, path: "b"
  # colocou para mostrar "localhost:3000/b/1" na URL "AMIGÁVEL"
  root "blog_posts#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_rich_text :body
  has_one_attached :meta_image
  has_one_attached :banner_image
end

app/controllers/admins/sessions_controller.rb
module Admins
  class SessionsController < ApplicationController
    skip_before_action :authenticate_admin!, only: [:new, :create]
    before_action :set_title, only: [:new]

    def new
      @admin = Admin.new
    end

    def create
      @admin = Admin.find_by(email: params[:admin][:email])
      if @admin&.authenticate(params[:admin][:password])
        session[:admin_id] = @admin.id
        redirect_to admin_root_path, notice: 'Login efetuado com sucesso.'
      else
        flash.now[:alert] = 'Email ou senha inválidos.'
        render :new
      end
    end

    def destroy
      session.delete(:admin_id)
      redirect_to root_path, notice: 'Logout efetuado com sucesso.'
    end

    private

    def set_title
      @title = 'Login'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  before_action :authenticate_admin!, except: %i[ index show ]
  before_action :set_blog_post, only: %i[ show edit update destroy ]

  def index
    @blog_posts = BlogPost.all
  end

  def show;end

  def new
    @blog_post = BlogPost.new
  end

  def edit;end

  def create
    @blog_post = BlogPost.new(blog_post_params)

    if @blog_post.save
      redirect_to @blog_post, notice: "Conteúdo criado com sucesso."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post, notice: "Conteúdo atualizado com sucesso."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy!

      redirect_to blog_posts_path, status: :see_other, notice: "Conteúdo apagado com sucesso."
  end

  private
  def record_not_found
    flash[:alert] = "Conteúdo não encontrado."
    redirect_to root_path
  end

  def set_blog_post
    # esse modo logo abaixo também funciona digitando,localhost:3000/b/1
    @blog_post = BlogPost.friendly.find(params.expect(:id))
  end

  def blog_post_params
    params.expect(blog_post: [ :title, :body, :meta_description, :meta_title, :meta_image, :banner_image, :tags ])
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_blog_post.html.erb
<div class="w-full h-96 rounded-lg bg-gray-200 flex flex-col group">
  <div class="w-full h-64">
    <% if blog_post.banner_image.attached? %>
      <%= image_tag blog_post.banner_image, class: "h-full w-full object-cover rounded-t-lg" %>
    <% else %>
      <%= image_tag "divertidamente.jpg", class: "h-full w-full object-cover rounded-t-lg" %>
    <% end %>
  </div>

  <div class="h-14 flex-shrink-0 w-full px-4 overflow-hidden text-ellipsis">
    <p class="text-xl text-gray-900 overflow-hidden font-semibold">
      <%= blog_post.title %>
    </p>
  </div>

  <div class="w-full h-full flex items-center px-4">
    <%= link_to "Ler Conteúdo", blog_post,
      class: "px-3 py-2 rounded-lg bg-gradient-to-r from-blue-500 to-purple-500 via-indigo-500 text-indigo-50 hover:scale-105" %>
  </div>
</div>

app/views/blog_posts/_form.html.erb
<%= simple_form_for blog_post, html: { class: "contents" } do |form| %>
  <% if blog_post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2>
        <%= pluralize(blog_post.errors.count, "error" ) %> prohibited this blog post from being saved:
      </h2>
      <ul class="list-disc ml-6">
        <% blog_post.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.input :title, input_html: {
    class: "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full focus:outline-none focus:ring-2" }, error_html:
    { class: "text-red-600 mt-1" }, wrapper_html: { class: "my-5" } %>

  <%= form.input :body, as: :rich_text_area, input_html: {
    class: "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full focus:outline-none focus:ring-2" },
    error_html: { class: "text-red-600 mt-1" }, wrapper_html: { class: "my-5" } %>

  <%= form.input :meta_description, as: :text, input_html: { rows: 4,
    class: "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full focus:outline-none focus:ring-2" },
    wrapper_html: { class: "my-5" } %>

  <%= form.input :meta_title, input_html: {
    class: "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full focus:outline-none focus:ring-2" },
    wrapper_html: { class: "my-5" } %>

  <%= form.input :meta_image, as: :file, input_html: {
    class: "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full focus:outline-none focus:ring-2" },
    wrapper_html: { class: "my-5" } %>

  <%= form.input :banner_image, as: :file, input_html: {
    class: "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full focus:outline-none focus:ring-2" },
    wrapper_html: { class: "my-5" } %>

  <%= form.input :tags, as: :text, input_html: { rows: 4,
    class: "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full focus:outline-none focus:ring-2" },
    wrapper_html: { class: "my-5" } %>

  <div class="my-5">
    <%= form.button :submit,
      class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<% content_for :title, "Editing blog post" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Alterando dados do Conteúdo</h1>

  <%= render "form", blog_post: @blog_post %>

  <%= link_to "Voltar", blog_posts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/blog_posts/index.html.erb
<% content_for :title, "Blog posts" %>

  <div class="w-full">
    <div class="flex justify-between items-center">
      <h1 class="font-bold text-4xl">Uso do FlowBite</h1>
      <%= link_to "Novo Conteúdo", new_blog_post_path,
        class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
    </div>

    <div id="blog_posts" class="min-w-full grid md:grid-cols-3 lg:grid-cols-4 gap-4 mt-8">
      <%= render @blog_posts %>
    </div>
  </div>

app/views/blog_posts/new.html.erb
<% content_for :title, "New blog post" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Criando Conteúdo</h1>

  <%= render "form", blog_post: @blog_post %>

  <%= link_to "Voltar", blog_posts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/blog_posts/show.html.erb
<% content_for :title, @blog_post.title %>
<div class="md:w-2/3 w-full">

  <% content_for :head do %>
    <meta property="og:title" content="<%= @blog_post.title %>" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= url_for(@blog_post.meta_image) if @blog_post.meta_image.attached? %>" />
    <meta name="description" content="<%= @blog_post.meta_description %>">

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@blogapp" />
    <meta name="twitter:title" content="<%= @blog_post.title %>>" />
    <meta name="twitter:description" content="<%= @blog_post.meta_description %>" />
    <meta name="twitter:image" content="<%= url_for(@blog_post.meta_image) if @blog_post.meta_image.attached? %>" />
  <% end %>

    <div class="flex gap-2 mb-4">
      <%= link_to "Listar Conteúdos", blog_posts_path, class: "text-xl text-gray-900 hover:underline" %>
      <%= link_to "> #{@blog_post.title}", @blog_post, class: "text-xl text-gray-900 hover:underline" %>
    </div>

  <div class="flex flex-col w-full">
    <%= image_tag(@blog_post.banner_image, class: "w-full h-64 object-cover" ) if @blog_post.banner_image.attached? %>

    <h6 class="font-bold text-1xl">Detalhes do Conteúdo</h6>

    <div class="my-8 flex flex-col gap-4">
      <div>
        <%= @blog_post.body %>
      </div>
      <span> Tags: <%= @blog_post.tags %> </span>
    </div>
  </div>

  <%= link_to "Alterar", edit_blog_post_path(@blog_post), class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Cancelar", blog_posts_path, class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Deletar", @blog_post, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Tem Certeza ?" } %>
</div>

app/views/layouts/_admin.html.erb
<span> Adminstrador Logado > <%= current_admin.email %></span>
<%= button_to "Sair", destroy_admin_session_path, method: :delete, class: "ml-2 text-blue-600 hover:underline" %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, message| %>
  <div class="mb-4 px-4 py-3 rounded-md text-white
        <%= key == 'alert' ? 'bg-red-500' : 'bg-green-500' %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Flowbiteblog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%#= render "layouts/header" %>
    <%= render "layouts/admin" if current_admin %>
    <%= render "layouts/flash_messages" %>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>